---
# This playbook should update datadog-agent where applicable and install required pip package jsonpath-rw as appropriate

  - name: Update datadog across all servers where its required
    hosts: all
    roles:
      - common
