---

- name: reboot host
  shell: sleep 2 && shutdown -r now "Ansible updates and firewall config applied, reboot requested"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true

- name: Wait for host to come back up
  local_action: wait_for host="{{ ansible_ssh_host | default(inventory_hostname) }}" timeout=300 delay=30 state=started port=22
  sudo: false

- name: Pause briefly for ssh to be responsive
  pause: seconds=15

- name: Get uptime output
  shell: uptime
  register: output
  sudo: false

- name: Display output
  debug: msg=result.stdout

